### ISSUE TITLE
RSMTool does not support half-point rounded scores.

### ISSUE THREAD

**Issue by bndgyawali** [EducationalTestingService/rsmtool#101]

**Comment by aloukina** [comment]
We probably do not want to build in the logic of trying to guess the level of rounding for human scores and the types of evaluation that might be appropriate: the simplest solution is for the user to write their own custom notebook with the required analyses. If we find a particular rounding logic is common, we might hard-code it later.


However, some of our evaluations only work with integer human scores and therefore are meaningless for real-values scores:

confusion matrix
kappa

For these evaluations we internally round the human scores without warning. What we want to do is to skip these evaluations if human scores are not rounded and display a note explaining why.

Binod Gyawali has test case.

**Comment by desilinguist** [comment]
I think we can just add some warnings to the command line and to the appropriate notebooks to show that rounding has happened to non-integer scores. I am not sure that we need to skip kappa and the confusion matrix.

**Comment by desilinguist** [comment]
Addressed by #176.
