### ISSUE TITLE
Option to load images as clickable thumbnails in HTML report

### ISSUE THREAD

**Issue by jbiggsets** [EducationalTestingService/rsmtool#113]
Large HTML reports with lots of images can take a very long time to load. It would be helpful to allow users to generate clickable thumbnail images (rather than full-sized images) in the report. The images can be saved in the `figures` folder.

In addition, it may be useful to produce a zipped version of the experiment.

**Comment by desilinguist** [comment]
I guess the second part of this (creating a zip file) will be addressed in a separate PR?

**Comment by desilinguist** [comment]
Addressed by #142.
