### ISSUE TITLE
Warning in rsmcompare when computing summary evaluations

### ISSUE THREAD

**Issue by jbiggsets** [EducationalTestingService/rsmtool#119]
In the old code, `load_rsmtool_output` in `compare.py` called `make_summary_stat_df` which in turn computed the medians of various values.

For some unknown reason, we actually call that functions for all kinds of things that do not later make it into the report like partial correlations by group etc.

When some of the subgroups have small N and therefore NaNs for either marginal or partial correlations, the old `make_summary_stat_df` function would print a warning when trying to compute the summary stat. 

We can probably just suppress that warning.

The branch contains the test that actually fails not because of the warning but because of something else that I did not have time to investigate.

**Comment by aloukina** [comment]
@jbiggsets What is the failing test?

**Comment by desilinguist** [comment]
Addressed by #140.
