### ISSUE TITLE
Allow user to specify objective for SKLL models

### ISSUE THREAD

**Issue by jbiggsets** [EducationalTestingService/rsmtool#122]
We are currently forcing the objective to be pearson.

Also, display the objective used in the report.

And potentially change the default from pearson to neg_mean_error.

**Comment by desilinguist** [comment]
Here's what I am thinking about how to implement this: 
1. I will add an `objective` option to the config file which will have a default value of `neg_mean_squared_error` that SKLL knows about.  For SKLL 2.0, the goal is to not have a default at all and let the objective entirely be the user's responsibility but RSMTool is somewhat different from SKLL in that there are built-in learners for which there is _no_ (explicit) tuning required and most of them use MSE as the objective for their analytical solutions.
2. If the user specifies an objective for a non-SKLL model, I'll print a warning saying that it will be ignored.
3. I will also display the tuning objective in the report for SKLL models.
