### ISSUE TITLE
Allow specifying features as a list in the config file

### ISSUE THREAD

**Issue by jbiggsets** [EducationalTestingService/rsmtool#124]
We should allow `features` to be a field that can also take a list of feature names so that people don't have to make a JSON file if all they want to do is to use the raw features without transforming them. More advanced users who want to play with the signs and transforms can use the JSON file.

**Comment by desilinguist** [comment]
This should be easy to do by just taking the list of features and just creating the same object that DataContainer reads in from disk by using `add_frame()`. Just don't pass in the feature file to the data container in the beginning (so that it's not read later since it won't be on disk)

**Comment by desilinguist** [comment]
Addressed by #147.
