### ISSUE TITLE
Links to .csv files from .html report

### ISSUE THREAD

**Issue by jbiggsets** [EducationalTestingService/rsmtool#126]
It could be useful to have links in .html report which would allow you to immediately open the specific .csv files for this given analysis rather than asking people to remember our sometimes not very transparent naming scheme. I was just trying to show all of this to Jay and it's a bit messy even with output_csv.md file.  The problem is of course that if the report is forwarded without the output folder the links will be lost. 

 A perhaps better alternative could be to generate a separate .html report which contains only explanations+links to available .csv files and store this report under output. Then somebody from IDEAS who ran the tool and then wants to play around with .csv could quickly locate them by using this "report".

**Comment by desilinguist** [comment]
I think we can easily have links next to the sections/tables where the CSV files are used.

**Comment by desilinguist** [comment]
Addressed by #153.
