### ISSUE TITLE
Allow using SKLL classifiers with probability output

### ISSUE THREAD

**Issue by aloukina** [EducationalTestingService/rsmtool#129]

**Comment by desilinguist** [comment]
I am not really sure what this means. Is this to allow the user to use expected values as predictions?

**Comment by aloukina** [comment]
Yes, to give user access to the same approach as you used in BEA paper: "Therefore, for all four classifiers, we use the predict_proba() method of their scikit-learn implementations to obtain probability distributions over the possible score points and then compute the expected value using the distribution as the final classifier prediction."

**Comment by desilinguist** [comment]
Addressed by #156.
