### ISSUE TITLE
Quoted boolean values misinterpreted in config files

### ISSUE THREAD

**Issue by mulhod** [EducationalTestingService/rsmtool#13]
Valid boolean values in JSON files do not include quotation marks surrounding the values, so, if these values *are* surrounded by quotation marks in RSMTool configuration files, the values are not interpreted correctly (or do not raise an exception that might be helpful in identifying the problem). For example, if `exclude_zero_scores` is set to `"false"` (rather than `false`) in an RSMEval configuration file, it will still be interpreted as `True` and could log a confusing warning to that effect. If not changed to accepte quoted boolean values, then maybe the invalid value can just be rejected immediately and a helpful error message could be displayed.

**Comment by desilinguist** [comment]
Addressed by #15.
