### ISSUE TITLE
API in refactored version

### ISSUE THREAD

**Issue by aloukina** [EducationalTestingService/rsmtool#130]
The following functions from API are used in other research scripts:
`from rsmtool.analysis import metrics_helper`
`from rsmtool.report import convert_ipynb_to_html`
`from rsmtool.preprocess import remove_outliers`

Would be good to check if it's possible to keep those available with a deprecation warning or a document suggesting how to achieve the same functionality?

**Comment by desilinguist** [comment]
They all seem to be static methods so we can easily provide a place in the DOCS where we say, if you were using `f()`, now you need to do XYZ to use it.

**Comment by desilinguist** [comment]
There definitely needs to be a bigger issue about updating the API page to list all of the static methods and/or instance methods that we think are likely to be generally useful.

As for this specific issue, I think we can just tell people in the release notes to look at the API page if they used these older functions to find replacements. No need to have anything explicit in the documentation.

**Comment by desilinguist** [comment]
Just have an extra page that's linked to from the API page at the top and don't worry about the release notes.

**Comment by desilinguist** [comment]
Addressed by #173.
