### ISSUE TITLE
Check utility scripts and other auxiliary files

### ISSUE THREAD

**Issue by aloukina** [EducationalTestingService/rsmtool#164]
Before replacing `master` with `rsmtool-refactor` we should go over various utility scripts in `master` as well as other auxiliary files to make sure nothing useful got lost in transit.

**Comment by aloukina** [comment]
Here are the two files I identified. Both don't need to be moved. 

`convert_feature_jsons_in_tests.py` - converts feature files from old `.json` format to current `.csv `format. The script is specifically written to convert `tests` file. We will not need to run this again so it can stay in `master`. 

`make_test_data.py` - converts original ASAP file to test data. We have not run it since the original file generation and have since made manual changes to the automatically generated file. So I suggest we don't need this.

**Comment by jbiggsets** [comment]
Agreed. Closing this and no resolution needed.
