### ISSUE TITLE
Allow user to exclude Intermediate files section

### ISSUE THREAD

**Issue by aloukina** [EducationalTestingService/rsmtool#179]
At the moment the `intermediate_files` section is included by default which means that if the user chose to only share `.html` report, the final section will contain broken links.
One can avoid this by specifying the list of sections but it is not a very user-friendly solution.
Perhaps we could consider adding a configuration setting `Include_links` that could be set to `False` in case the person generating the report does not want to include them?

**Comment by desilinguist** [comment]
Can we combine this with #177 for the upcoming release?

**Comment by aloukina** [comment]
Not sure we need this any more. With interactive config generation it is now very simple to customize the list of sections so it doesn't make much sense to add machinery just for this section.

**Comment by desilinguist** [comment]
Agreed. I'll close it as wontfix.
