### ISSUE TITLE
Non-integer human scores

### ISSUE THREAD

**Issue by desilinguist** [EducationalTestingService/rsmtool#189]
Some of our evaluations only work with integer human scores:

- confusion matrix
- kappa

For these evaluations we internally round the human scores without warning. What we want to do is to skip these evaluations if human scores are not rounded and display a note explaining why.

If the user needs those, they will need to come up with their own special notebooks since the "rounding" logic may differ vastly across applications. If we find a particular rounding logic is common, we might hard-code it later.

**Comment by desilinguist** [comment]
Addressed by #176.

**Comment by aloukina** [comment]
Duplicate https://github.com/EducationalTestingService/rsmtool/issues/101
