### ISSUE TITLE
Incorporate all-subsets regression into `rsmtool`

### ISSUE THREAD

**Issue by jbiggsets** [EducationalTestingService/rsmtool#195]
Perhaps we could incorporate all-subsets regression into `rsmtool` as one possible model type.

**Comment by desilinguist** [comment]
Is this already done or are we still working on it?

**Comment by desilinguist** [comment]
What’s going on with this issue? Are we planning on doing this?

**Comment by jbiggsets** [comment]
We decided not to incorporate this into RSMTool. It didn't seem like there was much interest.
