### ISSUE TITLE
Make it easy to debug ipynb file if the rendering fails

### ISSUE THREAD

**Issue by desilinguist** [EducationalTestingService/rsmtool#199]
Right now, if something goes wrong on in the rendering part, we need to manually set a whole lot of environment variables to run the ipynb file interactively. It would be nice if there was a way we could do that automatically in some debug mode or something.

**Comment by jbiggsets** [comment]
We now save a hidden `.environ.json` file that can be loaded when he notebook is run interactively. We do not need to manually set these environment variables anymore. 

See issue #241.
