### ISSUE TITLE
The `preprocessed_features` notebook hangs when using a large number of features

### ISSUE THREAD

**Issue by jbiggsets** [EducationalTestingService/rsmtool#202]
When the number of features is large, the `preprocessed_features` notebook hangs, and the report generation times out. The bottleneck seems to be the training set distribution graphs in this notebook.

It would be useful to update this notebook in one of two ways: (1) if the number of features is greater than some threshold X, the histograms are dropped, or preferably, (2) a random subset of the data is used to generate histograms, with a warning to the user that the histograms are not based on the full dataset.

**Comment by jbiggsets** [comment]
This was originally an issue with `kde=True`. However, with a large number of features, it still appears that this notebook can time out. Looking into this more.

**Comment by desilinguist** [comment]
Is this still an issue @jbiggsets ?
