### ISSUE TITLE
support .jsonlines input format

### ISSUE THREAD

**Issue by aoifecahill** [EducationalTestingService/rsmtool#244]
It would be nice if rsmtool could support the .jsonlines input format that skll also supports. This would make it easier to get some of the additional benefits that rsmtool offers over skll without having to convert data files (sometimes from sparse to dense formats).

**Comment by aloukina** [comment]
@aoifecahill We wouldn't be able to support sparse formats properly since any response with null values for any feature is removed from training/evaluation. Do you ever use jsonlines for non-sparse data?

**Comment by aoifecahill** [comment]
Hmm, we do actually use jsonlines for non-sparse data sometimes.

**Comment by aloukina** [comment]
@aoifecahill Can you think of a situation where you might want output files as `.jsonlines` ?

**Comment by aoifecahill** [comment]
Not off the top of my head. We are used to getting the outputs in .csv and so our scripts are set up for that.

**Comment by desilinguist** [comment]
Addressed by #271
