### ISSUE TITLE
Dependency chain is huge

### ISSUE THREAD

**Issue by jkahn** [EducationalTestingService/rsmtool#25]
I think at least the `jupyter` dependencies should be installed separately (perhaps in a `notebook` extra?)

**Comment by jkahn** [comment]
Mentioning because install procedure is complicated and finding it in @desilinguist 's conda repo is not where I ordinarily expect to find packages. https://github.com/openjournals/joss-reviews/issues/33

**Comment by desilinguist** [comment]
They are all needed for producing the report.

**Comment by desilinguist** [comment]
I'm confused. The install procedure is one command. Are you not able to
install it using that one command?

**Comment by jkahn** [comment]
You actually need jupyter and all its dependencies to run a commandline
tool?

**Comment by desilinguist** [comment]
The main goal of RSMTool is to produce a comprehensive HTML report which is
generated by dynamically rendering an ipython notebook. Yes, you need
Jupyter and all its dependencies for that.

**Comment by jkahn** [comment]
ok. I think I misunderstood the scope of this project.  I've got the installation working with conda. I'll try a separate but related issue which is that the `pip` installation from source seems to succeed with far less download -- probably a bug in specifying pip dependencies.

**Comment by desilinguist** [comment]
I actually would advise users against doing a pip install. This is why the
readme explicitly states that you need conda.
