### ISSUE TITLE
Don't update user's jupyter history when notebooks are executed

### ISSUE THREAD

**Issue by mulhod** [EducationalTestingService/rsmtool#250]
When notebooks are executed, all of the cells are added to the user's history each time they are executed. This clogs up the history and makes it hard to use history-related functionality like search. Because the cells are large, it also makes it hard to use practically since the cells take up the whole screen (or multiple pages of a screen even). In any case, a user is not likely to want to find a cell executed as part of RSMTool notebooks. So, it would be great if we could find a way to run notebooks in a sort of sandbox, if possible.

**Comment by aloukina** [comment]
@mulhod Is this something you are still planning to address/see as an issue?

**Comment by desilinguist** [comment]
@mulhod ☝️ ?
