### ISSUE TITLE
Only show fairness evaluation introduction when subgroups are specified

### ISSUE THREAD

**Issue by desilinguist** [EducationalTestingService/rsmtool#282]
Right now, if you don't specify any sections the fairness evaluation introduction shows up even if you don't have any subgroups which is probably not what we want. See image below.

![image](https://user-images.githubusercontent.com/161680/64713516-fdca9c00-d48a-11e9-95eb-42126dee1068.png)

**Comment by aloukina** [comment]
There is a fix for this in read_jsonelines PR

**Comment by desilinguist** [comment]
Addressed by #271
