### ISSUE TITLE
Switch to alternative formula for QWK

### ISSUE THREAD

**Issue by aloukina** [EducationalTestingService/rsmtool#296]
There are two equivalent formulas for QWK: 
<img width="477" alt="Screen Shot 2019-09-23 at 16 41 43" src="https://user-images.githubusercontent.com/16725768/65461110-500fa380-de21-11e9-9af6-ef1251a6c295.png">

@jbiggsets  used the first formula which is what I documented. 
Both formulas are present in Shelby's article but the first one is given in a form that is likely to  be obscure to a non-statistician while the second one would be readable to a larger group of people (https://onlinelibrary.wiley.com/doi/epdf/10.1002/ets2.12258, p. 7). Perhaps we should change the code and documentation to the second formula for transparency and to make it clearly traceable to the publication?

**Comment by aloukina** [comment]
Note that the two formulas produce identical results when variance and covariance are those for the population, that is they are computed by dividing by N and not n-1. In this case the output for discreet values also matches the outputs from sklearn or skll.

**Comment by desilinguist** [comment]
Addressed by #301
