### ISSUE TITLE
Change headers and potentially section order in the report

### ISSUE THREAD

**Issue by aloukina** [EducationalTestingService/rsmtool#306]
The header for the True score evaluations needs to be moved one level up so that it doesn't appear under Fairness evaluations. I would also move it before subgroup analyses.
<img width="510" alt="Screen Shot 2019-10-10 at 12 45 33" src="https://user-images.githubusercontent.com/16725768/66589169-efd86b80-eb5b-11e9-929a-3ddb6861dd46.png">

**Comment by desilinguist** [comment]
Addressed by #307.
