### ISSUE TITLE
Additional checks for notebooks that require H2

### ISSUE THREAD

**Issue by aloukina** [EducationalTestingService/rsmtool#315]
We currently check in the reporter whether any of the requested notebooks require subgroups and if those were specified. For notebooks that require H2 we simply quietly omit the content if there is no H2. It will be more consistent to raise an error in the same way as we do for subgroups (https://github.com/EducationalTestingService/rsmtool/blob/a8f674f540e41e0188d90f96db32813c76f7f39b/rsmtool/reporter.py#L391)

**Comment by aloukina** [comment]
Things got more complex since we last filed it. The original idea was to treat `second_score` as `subgroups` in https://github.com/EducationalTestingService/rsmtool/blob/44e60059d10d919a8de24996e153f4fadcdbbcac/rsmtool/reporter.py#L330

However since then two things happened:
- PRMSE section is displayed if the user specified H2 OR if they specified `rater_error_variance` and no h2. This means we'll need different logic for PRMSE notebook vs. consistency.
- We will need to propagate both of these to interactive config generation which to me sounds like an overkill. 

The original issue emerged because a user was wondering why they didn't see PRMSE results even though they explicitly requested this section (they didn't have h2). Our notebook is set up to just skip the whole section (incl heading) if there is no h2 (or rater error variance now)

Proposed solution: show section heading if the user requested the section (explicitly or implicitly) with the message that the analyses were not run because there is no h2.

**Comment by desilinguist** [comment]
Yes, just showing a message in the notebook sounds like the better option to me!
