### ISSUE TITLE
Unpin jupyter_console

### ISSUE THREAD

**Issue by jbiggsets** [EducationalTestingService/rsmtool#323]
We are currently pinning `jupyter_console==6.0.0` in the `requirements.txt` and `environment.yml` files. This is due to a version incompatibility error with `prompt-toolkit`:

```
ERROR: ipython 7.10.1 has requirement prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0, but you'll have prompt-toolkit 1.0.18 which is incompatible.
```

We investigated this and found that the error was introduced by a downgrade of `jupyter_console` from version `6.0.0` to` 5.2.0`. Once this gets resolved, we should be able to unpin the `jupyter_console` package.

**Comment by desilinguist** [comment]
Addressed by #362.
