### ISSUE TITLE
Retrain all model stored in tests for RSMPredict

### ISSUE THREAD

**Issue by aloukina** [EducationalTestingService/rsmtool#344]
The tests for RSMPredict include trained models. We need to re-train them using the updated environment with sklearn 0.21.3. These should be done after we resolved errors in #339.

There is a script for doing this: https://github.com/EducationalTestingService/rsmtool/blob/master/tests/update_skll_models.py

The script has not yet been tested with new SKLL/sklearn. 

This will take care of the following UserWarnings that occur when running the tests:
`UserWarning: Trying to unpickle estimator LinearRegression from version 0.19.1 when using version 0.21.3. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)`

**Comment by desilinguist** [comment]
Addressed by #349.
