### ISSUE TITLE
Deprecation warning for xlsx

### ISSUE THREAD

**Issue by aloukina** [EducationalTestingService/rsmtool#345]
We get the following deprecation warning when using xlsx: 

`python3.7/site-packages/xlrd/xlsx.py:266: PendingDeprecationWarning: This method will be removed in future versions.  Use 'tree.iter()' or 'list(tree.iter())' instead.`

**Comment by mulhod** [comment]
@aloukina Can you point me to a situation where this happens. So far, I don't see it happening anywhere when I run the tests and I don't even see it happening when I open an IPython session and try to use `read_excel` directly to trigger a warning.

**Comment by aloukina** [comment]
My version of `xlrd` is 1.2.0, running on macOS.

This is raised by the following tests:
**test_reader.TestDataReader:**

multiple tests, including:
 * .test_add_containers_duplicate_keys
 * .test_container_feature_specs_property
 * .test_container_train_property
 * .test_getitem_test_from_key


**test_writer.TestDataWriter**
  * .test_data_container_save_files
  * .test_data_container_save_files_with_id 
  * .test_dictionary_save_files

**Comment by mulhod** [comment]
It's strange. I don't see any warnings when I run the tests. For example:

```
$ nosetests --nologcapture tests/test_reader.py:TestDataReader.test_add_containers_duplicate_keys
.
----------------------------------------------------------------------
Ran 1 test in 0.156s

OK
```

**Comment by mulhod** [comment]
Would the deprecation warning be expected to show up in the CI build? https://travis-ci.org/EducationalTestingService/rsmtool/jobs/643938322?utm_medium=notification&utm_source=github_status

I don't think I see them there either.

**Comment by desilinguist** [comment]
@mulhod are you using the same version of `xlrd` as @aloukina ?

**Comment by mulhod** [comment]
@desilinguist Yes. I am:
```
$ conda list -p ../rsm_env | grep xlrd
xlrd                      1.2.0                    pypi_0    pypi
```

**Comment by aloukina** [comment]
This might be relevant: https://github.com/pandas-dev/pandas/issues/28547

**Comment by desilinguist** [comment]
So, shall we also move to `openpyxl` then?

**Comment by aloukina** [comment]
We are calling `read_excel` and `to_excel`, not calling `xlrd` directly.

**Comment by desilinguist** [comment]
yeah, I realized that as soon as I posted and then deleted my message :)

**Comment by aloukina** [comment]
Closing because we are not seeing this warning in tests anymore.
