### ISSUE TITLE
LinearSVR fails to converge in new version

### ISSUE THREAD

**Issue by aloukina** [EducationalTestingService/rsmtool#351]
After switching to scipy 1.4.1 we get the following warning in tests:
`envs/rsmtool_skll/lib/python3.7/site-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.`

I have re-run the tests using old environment and can confirm that this warning is new.

**Comment by aloukina** [comment]
@desilinguist Any thoughts on this? We are using default settings when calling skll:

https://github.com/EducationalTestingService/rsmtool/blob/07f91264795dc8fb5de9518cb65ff4e1685836ef/rsmtool/modeler.py#L1057

**Comment by desilinguist** [comment]
Yeah, this is coming from scikit-learn, I think. I thought we had addressed this in SKLL v2.0 but may be we missed it?

**Comment by aloukina** [comment]
Do you have a test there that can check for this?

**Comment by desilinguist** [comment]
We have tests for SVMs but I don't think it gets triggered for the test data there. Which RSMTool test is this?

**Comment by aloukina** [comment]
linearsvr: https://github.com/EducationalTestingService/rsmtool/tree/master/tests/data/experiments/linearsvr

**Comment by desilinguist** [comment]
I don't think there's anything that can be done for this other than just suppressing the warnings in the test for now. For a small dataset like the one we use in this test (N=500), when we do grid search, the model fit just doesn't converge in the default 1000 iterations and with the given tolerance. To get the warnings to suppress, we'll need to bump up the tolerance and increase the number of iterations (see [here](https://github.com/EducationalTestingService/rsmtool/files/4188178/linearsvr-rsmtool.pdf)).

In the future, when we can pass in SKLL parameters to RSMTool, we can set the hyper-parameters of the model to suppress the warning.

**Comment by desilinguist** [comment]
Addressed by #361.
