### ISSUE TITLE
Add config generator

### ISSUE THREAD

**Issue by aloukina** [EducationalTestingService/rsmtool#354]
Several uses expressed interest in config generator. The concern is that it is sometimes hard to remember all fields and there names. 

We could have a script that you run as

`generate_config rsmtool --groups --consistency >config.json` 

which generates a json file with all fields. The defaults would be prefilled and the obligatory fields will be filled with "ENTER_INFO_HERE". It would also be really helpful to list all sections since it will make it easy to delete the ones you don't want to run.

In addition to CL script, I'd love this functionality exposed via API for using in Python notebooks.

The `--groups` and `--consistency` flags are necessary since some of the fields are conditioned on whether you want these. 

Another idea we discussed is to have the script prompt for user input (e.g. to allow tab completion for paths).

**Comment by desilinguist** [comment]
IMHO, it might be better to add a `quickstart` option to each of the tools rather than a separate script; something like:

```
rsmtool quickstart --with-groups --with-consistency > config.json
```

The implementation of this functionality could (and should) certainly be shared between the various utilities but I think in terms of exposing it to the user, this might be easier to remember. 

And if the user wants be prompted for each option, we could simply do:

```
rsmtool quickstart --interactive --with-groups --with-consistency
```

Thoughts?

**Comment by desilinguist** [comment]
Another thought - if we are going to use a pre-filled dummy value, it might be useful to have the respective script be aware of the value so that instead of just failing, it could say something like "it seems you are using a config generated via quickstart but you forgot to fill out some fields".

**Comment by aloukina** [comment]
Would `rsmtool quickstart ...` generate config and exit?

**Comment by desilinguist** [comment]
Yes. Does "quickstart" indicate to you that it should also run the config?

**Comment by aloukina** [comment]
To me it seems counterintuitive that the same command (`rsmtool`) is used for both running the experiment and generating config.

**Comment by desilinguist** [comment]
Ah, I see your point and that does seem like a valid concern. There are two ways to handle this:

(1) We move to `rsmtool` being the driver script and have it take a "command" as to what it's supposed to do. For example:

```
$> rsmtool run <config.json>
$> rsmtool quickstart --with consistency --with groups > config.json
```

We'd obviously have a backwards-compatible path, e.g.,  "run" could be the default command and old invocations would work just fine. This is the approach followed in many other large Python CLI projects and would give us a good expansion path for future commands. 

(2) We stick with your suggestion and just tweak it a bit:

```
$> quickstart --for rsmtool --with sources --with consistency > config.json
$> quickstart --for rsmeval --interactive
```

**Comment by aloukina** [comment]
I like both with preference for 1 because it could be expanded to `rsmtool eval` etc.

**Comment by desilinguist** [comment]
This will be done in two parts:
- [ ] Add basic harness for automated generation and implement non-interactive generation
- [ ] Add interactive configuration generation.
