### ISSUE TITLE
Allow run_* functions to take dictionary as input

### ISSUE THREAD

**Issue by aloukina** [EducationalTestingService/rsmtool#355]
Currently the main API functions `run_experiment`, `run_evaluation` etc. take either file path to the config file or a valid `Configuration` object with all missing fields set to default values. Constructing and validating such object requires an in-depth understanding of the interplay between `Configuration` and `ConfigurationParser`.

It will be simpler to allow user pass a file path, object or a dictionary that will then be normalized, vadlidated and converted to a Configuration object.

**Comment by desilinguist** [comment]
Addressed by #356 and #371.
