### ISSUE TITLE
More meaningful error message for non-numeric features

### ISSUE THREAD

**Issue by aloukina** [EducationalTestingService/rsmtool#389]
It would be helpful to print a more explicit message, if one of the features only contains non-numeric values specifying the name of the feature. 

This should be done here: 

https://github.com/EducationalTestingService/rsmtool/blob/0eb9a96e236828483123e46a4b1e2f1376c59827/rsmtool/preprocessor.py#L753

**Comment by desilinguist** [comment]
@aloukina I am working on this but I am a little confused. The method you link to works for a given column so what does "one of the features ..." mean in this context?

**Comment by aloukina** [comment]
The context is somebody having a feature that is fully non-numeric, so this line https://github.com/EducationalTestingService/rsmtool/blob/0eb9a96e236828483123e46a4b1e2f1376c59827/rsmtool/preprocessor.py#L813 drops every single value. I am not sure whether we just ignore the feature in this case or throw an obscure error later one. What we want is to raise error/warning at this point that "Feature `column` contained only non-numeric values (and was dropped if we are raising a warning)". I don't think we need to change the actual behavior (raise error vs. drop).

**Comment by desilinguist** [comment]
Okay, so just add a warning saying that the given column only contained non-numeric values of the number of bad rows equals the length of the data frame?

**Comment by aloukina** [comment]
May be check if this breaks things later on in which case we need to raise an error?
