### ISSUE TITLE
Make check in RSMTool more explicit

### ISSUE THREAD

**Issue by desilinguist** [EducationalTestingService/rsmtool#393]
There's a currently [a place in RSMTool](https://github.com/EducationalTestingService/rsmtool/blob/master/rsmtool/rsmtool.py#L286) where we raise a `ValueError` if a coefficients file already exists in the output directory. There's no documentation as to why this is being checked.

From @aloukina, this is why we do this:

> This is what I think it’s doing in a roundabout way: it uses the existence of coefficients file as a shortcut to establish that we are dealing with a linear model.  If you first run a LR experiment and then followed it with SVR using the same id and the same output_directory, you’ll get this error. The coefficients file will be there but the modeler will not be able to scale them because [these lines](https://github.com/EducationalTestingService/rsmtool/blob/0eb9a96e236828483123e46a4b1e2f1376c59827/rsmtool/modeler.py#L1422) will fail. 

We should replace this roundabout check with a much more explicit check, e.g., simply testingwhether `predconfig.get_coefficients()` fails? That would make it much more readable.

**Comment by desilinguist** [comment]
@aloukina perhaps what we should do here is to just delete the original coefficients file and print a warning saying that an old coefficients file was detected and removed?

**Comment by aloukina** [comment]
I am more in favor or raising an error and letting the user do the clean up: if there is indeed an old LR experiment there, there would be other files too: coefficients_scaled, _model_fit, _betas etc. If these stay, it can create a lot of confusion down the line.

**Comment by aloukina** [comment]
Another solution is if the user specifies `-f` when running rsmtool, we first clean up any output with the same id from the output directories.

**Comment by desilinguist** [comment]
Hmm, I am not sure I want to change the semantics of `-f` at this juncture. 

How about if I modify `Modeler.scale_coefficients()` to raise an error if its call `get_cofficients()` fails since should be captured in the API too. And then tweak the error message in `rsmtool.py`? Would that work?

**Comment by aloukina** [comment]
The danger here is that we cannot really use `glob`:  if the user is not being very smart and has two experiments in the same folder, "exp1" and "exp1_updated" and then decide to re-run "exp1", we'll end up deleting both outputs unless we actually look for specific filenames.

**Comment by desilinguist** [comment]
Hmm, I am not sure I want to change the semantics of -f at this juncture.

How about if I modify Modeler.scale_coefficients() to raise an error if its call get_cofficients() fails since should be captured in the API too. And then tweak the error message in rsmtool.py? Would that work?

**Comment by aloukina** [comment]
So keep the general current logic but make the code more readable by testing for the right thing, right?

**Comment by desilinguist** [comment]
Yes!

**Comment by aloukina** [comment]
Yes, I like that!
