### ISSUE TITLE
Break up `utils.py` into `utils/*.py`

### ISSUE THREAD

**Issue by desilinguist** [EducationalTestingService/rsmtool#394]
Two reasons:
1. `utils.py` is getting really large. 
2. Circular imports are getting to be a problem. For example, I am writing utility functions that want to use classes from `configuration_parser.py` but `configuration_parser.py` also imports `utils.py` and this breaks things.

Looking at the code in `utils.py`, I think one reasonable  breakdown would be as follows:
- `utils/metrics.py`
-  `utils/notebook.py`
-  `utils/conversion.py`
-  `utils/logging.py`

**Comment by aloukina** [comment]
This makes perfect sense.
