### ISSUE TITLE
`CmdOption` broken on Python 3.6

### ISSUE THREAD

**Issue by desilinguist** [EducationalTestingService/rsmtool#401]
I just noticed that the ReadTheDocs build is failing and realized it’s because I am using a python 3.7-only keyword argument when defining the `rsmtool.utils.commandline.CmdOption` named tuple. ReadTheDocs uses python 3.6 to build the docs.

There are two solutions:
1. We drop support for python 3.6 with RSMTool 8 - this is not as radical as it sounds as python 3.8.2 is already out and stable and Python 3.9.0 will be out by the time we release RSMTool 8 (it’s already on its 4th alpha).
2. We implement a fix for Python 3.6 - it’s a little hacky but it’s only a single line of code. I just implemented it and it works.

Thoughts @aloukina @mulhod? @aoifecahill also tagging you because you might have some thoughts about what dropping python 3.6 means downstream.

**Comment by aloukina** [comment]
May be (2) for now if it's no additional work and deprecate in Summer?
I am not sure how many people have things pinned to 3.6.

**Comment by desilinguist** [comment]
Works for me!
