### ISSUE TITLE
Wishlist for interactive generation

### ISSUE THREAD

**Issue by aloukina** [EducationalTestingService/rsmtool#422]
Few things to add to interactive generation:
- Add `-i` flag (in addition  to ``--interactive``)
- Make subgroups an option rather than flag: "Do you have subgroups?" I always forget to set the flag.
- Add a question at the end: "Save output to a file?"

**Comment by desilinguist** [comment]
@aloukina how important is the subgroups bit for you? I ask because this would involve making several non-trivial changes to how the tests are setup and run.

**Comment by aloukina** [comment]
I thought it might be the case...

I found that I always forget to set the flag and then just add the fields manually, so the current approach is probably not very user friendly. Having said that, we don't need to do it in this release - we can keep it as a separate issue and revisit if we are making further changes to that code/once we have more feedback.

**Comment by desilinguist** [comment]
Hmm, okay. Let me take another look - perhaps there's a clever way of refactoring things that would make the change go down easier.

**Comment by desilinguist** [comment]
I am looking at the code and the main issue is right now, we can decide in advance what the sections should be but this change would introduce a dependency between two configuration fields (use subgroups and section list) which makes it a little messy. 

For now, I will just make `-g` an alias for `--subgroups` and hope that it makes it easier to remember. If we get many more complaints about this after we release, we can revisit it.

**Comment by desilinguist** [comment]
@aloukina for the saving thing, what if we just make it so that instead of printing to stdout, the generator always saves to the current directory with the name "<experiment_id>_<tool_name>.json"?

**Comment by aloukina** [comment]
In my opinion that would be worse  - you might overwrite something you already have etc. 
Copying from stdout is not a huge deal if saving under user-specified name is too involved.

**Comment by desilinguist** [comment]
The issue there is that every single interactive field we ask for is an actual configuration field whereas a field that asks for a user-specified name would _not_ be which requires additional shoe-horning in the code.

**Comment by aloukina** [comment]
For subgroups: how about a message in the beginning - "If you have subgroups, please exit the tool ('ctrl-D') and re-run with -g flag" . That would help me :)

**Comment by desilinguist** [comment]
> For subgroups: how about a message in the beginning - "If you have subgroups, please exit the tool ('ctrl-D') and re-run with -g flag" . That would help me :)

That's fine! I can do that!

**Comment by aloukina** [comment]
File saving: then let's just leave it as is.  It's not that much of a deal.

**Comment by desilinguist** [comment]
FYI, I just realized you can also do `rsmtool generate -ig` to specify interactive and subgroups together :)
