### ISSUE TITLE
Better handling of no arguments situation

### ISSUE THREAD

**Issue by aloukina** [EducationalTestingService/rsmtool#446]
If the user tries to run `rsmtool` with no arguments, they get an error from argument parser (list out of range). We should probably handle it more elegantly and in this case default to -h? Or at least show a helpful message?

**Comment by desilinguist** [comment]
Yeah, this should be an easy fix to just check to add [here](https://github.com/EducationalTestingService/rsmtool/blob/master/rsmtool/rsmtool.py#L353) based on len(sys.argv).
