### ISSUE TITLE
Tweak warning

### ISSUE THREAD

**Issue by etsuprun** [EducationalTestingService/rsmtool#460]
RSMTool issues the following warning if the `select_transformations` flag is set to True in config. However, it gives it even if a feature file is not specified and the list of features is directly fed into the experiment configuration.

> WARNING: You specified a feature file but also set `select_transformations` to True. Any transformations or signs specified in the feature file will be overwritten by the automatically selected transformations and signs.

https://github.com/EducationalTestingService/rsmtool/blob/27de5f63e78efe9d40ca3415513aab03c09f4eb9/rsmtool/configuration_parser.py#L997

**Comment by aloukina** [comment]
To address this, we need to check for the type of input in config['features'] and adjust the wording accordingly.
