### ISSUE TITLE
Change name of `master` branch

### ISSUE THREAD

**Issue by desilinguist** [EducationalTestingService/rsmtool#465]
We should rename the `master` branch to either `develop` or `main`.  We want to make sure that all the connections to the various external services like Travis, Azure, and ReadTheDocs is not interrupted.

**Comment by desilinguist** [comment]
This is a nice reference: https://medium.com/faun/git-step-by-step-renaming-a-master-branch-to-main-16390ca7577b

**Comment by srhrshr** [comment]
@desilinguist  - this is similar to the issue you raised on `skll`. But, I see that you have self-assigned this issue - let me know if you also want me to take this up - it should be similar to [the PR I raised on that repo](https://github.com/EducationalTestingService/skll/pull/626).

**Comment by desilinguist** [comment]
@srhrshr let's do the exact same here! I will  make a `main` branch and then you can make changes to that like you did for SKLL.

**Comment by srhrshr** [comment]
@desilinguist great - I've raised a PR here: #477.

**Comment by desilinguist** [comment]
This is now officially done! Thanks @srhrshr!
