### ISSUE TITLE
Allow custom range of human scores

### ISSUE THREAD

**Issue by aloukina** [EducationalTestingService/rsmtool#476]
In some situations, a user might only want to use a subset of human scores: e.g. 2-5 out of 0-5. 

We currently have a setting `exclude zero` which excludes zero scores, but there is no easy way to exclude 1 in the above scenario:

(1) One can use flag column to filter on first human score, but because of internal column renaming you need to set it to `sc1` rather than the original column name;

(2) `flag_column` may not give the expected result, if you also want to apply the same filter to the second human score (for consistency and PRMSE computations): unlike `sc1`, we do not automatically filter out responses with NaN or other non-numeric values in `sc2` for the main analyses, so to make this work one would need to define flags to cover all possible values including NaN but excluding 1.

We currently have a [optional] setting `trim_min` and `trim_max`. I wonder if we can extend it to also apply to human scores?
Alternatively it can be a new setting `human_score_range`.

**Comment by desilinguist** [comment]
This makes sense. I'd vote for a separate config option as the cleanest option.

BTW, what's a possible use case for this?

**Comment by aloukina** [comment]
For example, a score 1 is reserved for essays that are in correct English but are not on-topic. In this case for many applications such essays might be flagged by a separate module from the main scoring model.

**Comment by desilinguist** [comment]
Ah, got it.

**Comment by aloukina** [comment]
Asking around this seems to be a pretty niche use case. The simplest solution is for the user to recode the human score values they don't want to use into non-numeric values:  e.g. in my example above, the user would recode `1` to `one`.
