### ISSUE TITLE
JSON loading fails on valid JSON with parse_json_with_comments

### ISSUE THREAD

**Issue by mulhod** [EducationalTestingService/rsmtool#492]
I ran into an issue recently where I was using `parse_json_with_comments` and it failed despite there not being comments, actually.

This issue is not really about `rsmtool` for the most part, but the issue I ran into could have easily been an issue for `rsmtool` configuration files (perhaps in the free-text description fields, for instance).

Here is the offending JSON file:
```
{
    "advisories": {},
    "metadata": {
        "program": null,
        "score_max": 5,
        "score_min": 1
    },
    "multiple_models": false,
    "predict": {
        "trim_max": null,
        "trim_min": null
    },
    "read_data": {
        "data_to_plaintext": [
            "textpipes.pipes.CharFixerDefault",
            "textpipes.pipes.ReplaceTabsWithSpace",
            "textpipes.pipes.MultiSpaceToSingleSpace",
            "textpipes.pipes.Strip"
        ]
    },
    "text_to_instance": null,
    "train": {
        "notes": "The training process was recorded here: https://etsorg1-my.sharepoint.com/personal/briordan_ets_org/_layouts/15/Doc.aspx?sourcedoc={f3190115-91e2-4aac-bf28-3556a1669636}&action=edit&wd=target%28predict-scores-operational.one%7C3642acf5-3099-db40-9ddd-dc564ccc8dfb%2Fiteration-3%7C6b4bfc6b-5d8a-9e43-a382-9cc84884662b%2F%29",
        "repository_commit": "12.2020_model_deployment_1.0",
        "repository_name": "strides-scoring-pt",
        "repository_url": "https://stash.research.ets.org:7994/projects/BR/repos/strides-scoring-pt/browse",
        "train_cmd": "futil.run_experiment --config /home/research/mmulholland/text-dynamic/strides-scoring-pt/strides_scoring_pt/training_config/expt-3/expt-3_run_config.jsonnet --config_changes /home/research/mmulholland/text-dynamic/strides-scoring-pt/strides_scoring_pt/training_config/expt-3/expt-3_all_config_changes.jsonnet"
    }
}
```

It was the `"notes"` field that caused problems. Anyway, I confirmed that I could actually load in the JSON just fine with regular-old `json.loads` (like I said, there are no comments actually). But I was looking around for other libraries that did comment removal from JSON and stumbled on [`jsoncomment`](https://pypi.org/project/jsoncomment/0.2.3/). This library was actually able to load the JSON file above.

If you think it's worthwhile, I could try it out here.

**Comment by desilinguist** [comment]
Interesting. Do we know why it failed? Is it the URL?

**Comment by mulhod** [comment]
Yeah, it's the URL. I stepped through the code in a debugger and noticed that when it went through the replacements with the regex, it replaced part of it (which it shouldn't have been doing anyway), which caused it to then be invalid JSON.

**Comment by desilinguist** [comment]
Ah, I see. It doesn't look like `jsoncomment` is being actively developed though? Is it worth adding a new dependency just for this one thing? Other alternative might be:

1. Fix `parse_json_with_comments()` so that it handles URLs correctly. I think it's just the two slashes in `http://` that are causing the confusion. This can be easily fixed.

2. Make it clear that this function can _only_ handle comments of a specific type and does not work with URLs.

Thoughts?

**Comment by mulhod** [comment]
Yeah, I agree that it might not make sense to introduce a new dependency. However, I shared a not-up-to-date link to the `pypi` page above. It should have been: `https://pypi.org/project/jsoncomment/`. This shows that the most recent version as last year. Still probably a good bet that it's not being actively developed, though. There was a Conda package FWIW.

Anyway, I think fixing the function seems like a fine idea. `jsoncomment` did have a couple other things going for it, like allowing trailing commas. But still perhaps not enough to justify it.

**Comment by desilinguist** [comment]
Let's see what @aloukina thinks too

**Comment by aloukina** [comment]
Interesting. I cannot test it right now but I know we can handle urls generated by the interactive config generator. Those are in comments though. Does it mean we fail for urls in values?

My vote would be for fixing the function since we already have that rather than adding another dependency.
