### ISSUE TITLE
RSMCompare on RSMEval output can't find results

### ISSUE THREAD

**Issue by aoifecahill** [EducationalTestingService/rsmtool#50]
I'm running v 5.1.0 rsmcompare on two rsmeval outputs (generated with v 5.0.1), but the comparison report says that "This information is not available for either of the models.". If I look at the individual rsmeval reports, the information does seem to be there. 

In particular, I am looking at the following sections: consistency, score_distributions, evaluation

Is is that this rsmcompare comparison only works with reports generated with this version too? UPDATE: I just regenerated the rsmeval output using the latest version of rsmtool and am still having the same problem.

**Comment by aloukina** [comment]
The original config file contained incorrect experiment id. We added extra checks to make sure the user gets a meaningful error. 
Addressed by #51
