### ISSUE TITLE
Check if there are warnings in the reports and fix them if feasible

### ISSUE THREAD

**Issue by aloukina** [EducationalTestingService/rsmtool#538]
* Run the tests in strict mode
* Check for warnings
* Fix if necessary

**Comment by aloukina** [comment]
There are 70 failures. 

Some of the tests that failed:
 test_cli.TestToolCLI.test_run_good_overwrite
test_cli.TestToolCLI.test_run_without_output_directory
 test_experiment_rsmtool_1.test_run_experiment_lr_with_notebook_rerun
'lr', 'lr-subset-features', 'lr_with_feature_subset_file'

Warnings:

- Model diagnostic plot:

This warning comes from statmodels  and will need to be updated there:

``site-packages/statsmodels/graphics/gofplots.py:993: UserWarning: marker is redundantly defined by the 'marker' keyword argument and the fmt string "bo" (-> marker='o'). The keyword argument will take precedence.
  ax.plot(x, y, fmt, **plot_style)``

This has been already fixed: https://github.com/statsmodels/statsmodels/commit/1413df63e72e96bb4a5f6f17dce23fb28c7e4d20#diff-a54e08aa5988bca45a6df0d4eabd9793c2be36787bf681e4009c93747d1d47b8 but is not in the release package.

**Comment by desilinguist** [comment]
So all of the failures are just this statsmodels earning right @aloukina ?

**Comment by aloukina** [comment]
I added a line to ignore them (temporarily) and am re-running the tests to see if anything else comes up.

**Comment by aloukina** [comment]
I confirmed that the warnings above are the only warnings in the reports.
