### ISSUE TITLE
Cannot specify output file path when doing auto-generating configuration files 

### ISSUE THREAD

**Issue by damien2012eng** [EducationalTestingService/rsmtool#598]
When running `rsmtool generate --interactive > example_rsmtool.json`, interactive session gets stuck. 
It works fine without the `> example_rsmtool.json`.

**Comment by desilinguist** [comment]
Redirecting to files is no longer possible using `prompt_toolkit` (the library we are using for interactive input) without a lot of hacking around. The simpler solution is to simply ask the user where they want to save the generated file either when the process starts or ends. Once we have that, we can simply save the file at that path programmatically without relying on the redirect.
