### ISSUE TITLE
Unpin numpy in requirements and conda-recipe

### ISSUE THREAD

**Issue by tamarl08** [EducationalTestingService/rsmtool#644]
`numpy` is currently pinned to <1.25 due to an error in `numba`, should be unpinned when a new version of `numba` is available.

**Comment by desilinguist** [comment]
Here's the numba issue tracking the new release: https://github.com/numba/numba/issues/9122

**Comment by desilinguist** [comment]
@damien2012eng here's another issue we should look into in the short term if you happen to have time (cc: @tamarl08).

**Comment by desilinguist** [comment]
Closed via #666.
