### ISSUE TITLE
Update code to work with numpy 2

### ISSUE THREAD

**Issue by desilinguist** [EducationalTestingService/rsmtool#672]
Once numpy 2 has been out for a while, we should make sure that RSMTool works with numpy 2 and drop support for numpy 1, unless there's some serious issues with doing that

**Comment by damien2012eng** [comment]
Hi @desilinguist  Now the SKLL works with numpy 2. We can finally work on this issue.  Are we planning to any release for SKLL anytime soon?

**Comment by desilinguist** [comment]
We should do a SKLL 5.0.2 release? Do you have time to work on that?

**Comment by damien2012eng** [comment]
Yep. I’ll be able to work on the release early next week.
