### ISSUE TITLE
Separate runtime from development dependencies

### ISSUE THREAD

**Issue by twoertwein** [EducationalTestingService/rsmtool#678]
rsmtool lists many dependencies that are all installed when using pip/poetry. Some of these dependencies might only be required for development but not for users of rsmtool, e.g., pre-commit and jupyter.

It would be great to separate the runtime dependencies from the development dependencies (same applies to skll).

**Comment by desilinguist** [comment]
Welcome @twoertwein! You bring up a fair point that I have thought about multiple times but haven't really had time to execute on. We would welcome a PR if you have time to work on this!

**Comment by desilinguist** [comment]
Just to note that this is only an issue for users of `pip` and `poetry` which is something we haven't really thought about much since our primary method of installation is `conda` and the conda package does not install the dev dependencies. We should fix this for `pip` and `poetry` users.
