### ISSUE TITLE
allow specification of the trim tolerances

### ISSUE THREAD

**Issue by aoifecahill** [EducationalTestingService/rsmtool#96]
Currently they are fixed at +0.49998 and  -0.49998 which are reasonable, but it would be nice to be able to override them in certain situations.

**Comment by desilinguist** [comment]
@aoifecahill do you mean just via the API or also as an option for the config files?

**Comment by aoifecahill** [comment]
My use case was via the API, but could be useful for config files too I suppose?

**Comment by desilinguist** [comment]
Hmm, I think that would be a lot more involved so until someone specifically requests that, I will just make the API change for now.

**Comment by aoifecahill** [comment]
👍

**Comment by desilinguist** [comment]
Addressed by #106
